// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_blog_posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog articles from abelsalah.fr with title, slug, date, excerpt and tags. Covers AI strategy, sales automation, AI training and consulting insights (French).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of posts to return (default 20)."),
    tag: z.string().optional().describe("Optional case-insensitive tag filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, tag }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    const max = limit ?? 20;
    const url = `${supabaseUrl}/rest/v1/generated_blog_posts?select=slug,title,date,excerpt,tags,read_time&published=eq.true&order=date.desc&limit=${max}`;
    const res = await fetch(url, {
      headers: { apikey: anonKey, Authorization: `Bearer ${anonKey}` }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch posts: ${res.status}` }],
        isError: true
      };
    }
    let rows = await res.json();
    if (tag) {
      const t = tag.toLowerCase();
      rows = rows.filter((r) => (r.tags ?? []).some((x) => x.toLowerCase().includes(t)));
    }
    const posts = rows.map((r) => ({
      ...r,
      url: `https://abelsalah.fr/blog/${r.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts, null, 2) }],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/tools/get_blog_post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full content of a published blog post on abelsalah.fr by slug (returns title, meta, sections and public URL).",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug of the blog post (from list_blog_posts).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    const url = `${supabaseUrl}/rest/v1/generated_blog_posts?select=slug,title,meta_title,meta_description,date,read_time,tags,excerpt,content&published=eq.true&slug=eq.${encodeURIComponent(
      slug
    )}&limit=1`;
    const res = await fetch(url, {
      headers: { apikey: anonKey, Authorization: `Bearer ${anonKey}` }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch post: ${res.status}` }],
        isError: true
      };
    }
    const rows = await res.json();
    const post = rows[0];
    if (!post) {
      return {
        content: [{ type: "text", text: `No published post found for slug "${slug}".` }],
        isError: true
      };
    }
    const withUrl = { ...post, url: `https://abelsalah.fr/blog/${slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(withUrl, null, 2) }],
      structuredContent: { post: withUrl }
    };
  }
});

// src/lib/mcp/tools/list_ventures.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var ventures = [
  {
    name: "SCALLUP",
    url: "https://scallup.fr",
    tagline: "L'agent IA qui prospecte, relance et vend.",
    pitch: "Plateforme SaaS o\xF9 un agent IA ex\xE9cute les actions commerciales en pilote automatique : prospection multicanale, relances, appels, marketing, SEO, devis et pilotage.",
    metrics: ["500+ PME utilisatrices", "4.9/5 note moyenne", "Finan\xE7able OPCO"]
  },
  {
    name: "SKILL LMS",
    url: "https://skill-lms.fr",
    tagline: "Le LMS Qualiopi nouvelle g\xE9n\xE9ration.",
    pitch: "Plateforme tout-en-un pour organismes de formation : parcours, suivi apprenants, conventions, preuves Qualiopi, pilotage par IA.",
    metrics: ["Conformit\xE9 Qualiopi native", "Tout-en-un", "Relances & pilotage IA"]
  },
  {
    name: "FORMATEURS.PRO",
    url: "https://formateurs.pro",
    tagline: "Le plus grand annuaire de formateurs certifi\xE9s de France.",
    pitch: "Annuaire construit \xE0 partir de sources officielles (Pappers, INFOGREFFE, data.gouv.fr, France Comp\xE9tences). Connect\xE9 \xE0 SKILL LMS.",
    metrics: ["50 000+ formateurs r\xE9f\xE9renc\xE9s", "9 000+ certifi\xE9s Qualiopi", "98 % profils v\xE9rifi\xE9s"]
  },
  {
    name: "IMMO MONTPELLIER",
    url: "https://immomontpellier.com",
    tagline: "Le premier chasseur IA immobilier de Montpellier.",
    pitch: "L'IA scanne 8 sources en continu (SeLoger, Leboncoin, Bien'ici, PAP\u2026), alertes en moins d'1h, chasseur local pour visiter et n\xE9gocier jusqu'\xE0 la signature notari\xE9e.",
    metrics: ["8 sources scann\xE9es", "< 1h alerte", "Chasseur local"]
  }
];
var list_ventures_default = defineTool3({
  name: "list_ventures",
  title: "List ventures",
  description: "List the products and ventures built by Abel SALAH (SCALLUP, SKILL LMS, FORMATEURS.PRO, IMMO MONTPELLIER) \u2014 proof of AI + business execution.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ventures, null, 2) }],
    structuredContent: { ventures }
  })
});

// src/lib/mcp/tools/list_offers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var offers = [
  {
    slug: "audit-ia",
    title: "Audit IA pour PME & ETI",
    url: "https://abelsalah.fr/audit-ia",
    summary: "Diagnostic des processus, priorisation ROI des cas d'usage, roadmap 30/60/90 jours actionnable."
  },
  {
    slug: "automatisation-commerciale",
    title: "Automatisation commerciale par l'IA",
    url: "https://abelsalah.fr/automatisation-commerciale",
    summary: "Agents IA et workflows pour la prospection, la qualification, les relances et le pilotage commercial."
  },
  {
    slug: "formation-ia",
    title: "Formation IA pour \xE9quipes et dirigeants",
    url: "https://abelsalah.fr/formation-ia",
    summary: "Formation op\xE9rationnelle, coaching dirigeants, e-learning et routines d'adoption terrain."
  }
];
var list_offers_default = defineTool4({
  name: "list_offers",
  title: "List consulting offers",
  description: "List Abel SALAH's consulting offers (AI audit, sales automation, AI training) with URL and short summary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(offers, null, 2) }],
    structuredContent: { offers }
  })
});

// src/lib/mcp/tools/get_contact_info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  name: "Abel SALAH",
  role: "Consultant & Expert IA pour entreprises",
  website: "https://abelsalah.fr",
  booking: "https://tidycal.com/abelsalah/30min",
  linkedin: "https://www.linkedin.com/in/abel-salah/",
  youtube: "https://www.youtube.com/@abelsalah",
  cv: "https://abelsalah.fr/cv",
  note: "Contact exclusivement via booking Calendly/TidyCal \u2014 aucun formulaire public."
};
var get_contact_info_default = defineTool5({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return public contact and booking links for Abel SALAH (website, booking URL, LinkedIn, YouTube, CV).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "abel-salah-mcp",
  title: "Abel SALAH \u2014 Consultant IA",
  version: "0.1.0",
  instructions: "Public MCP server for abelsalah.fr. Use these tools to read Abel SALAH's blog articles (French, AI for business), consulting offers (AI audit, sales automation, AI training), ventures (SCALLUP, SKILL LMS, FORMATEURS.PRO, IMMO MONTPELLIER), and booking/contact links. All data is public \u2014 no authentication.",
  tools: [list_blog_posts_default, get_blog_post_default, list_ventures_default, list_offers_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
